name: Sync Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  sync_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create pull request in test-azure
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: 'Merge test branch to main'
          title: 'Merge test branch to main'
          branch: test-to-main
          base: main
          head: MSamson-MS:test
          repository: MSamson-MS/test-azure