name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test-github
        uses: actions/checkout@v2
        with:
          repository: MSamson-MS/test-github

      - name: Configure Git user
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"

      - name: Merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          # Get the pull request number
          PR_NUMBER=${{ github.event.pull_request.number }}

          # Clone the "test-azure" repository
          git clone https://github.com/MSamson-MS/test-azure.git

          # Go into the repository directory
          cd test-azure

          # Fetch the pull request branch
          git fetch origin pull/$PR_NUMBER/head:pr-merge-$PR_NUMBER

          # Checkout the pull request branch
          git checkout pr-merge-$PR_NUMBER

          # Merge the pull request branch into main
          git merge --no-ff pr-merge-$PR_NUMBER -m "Merge pull request #$PR_NUMBER"

          # Push the merged changes
          git push origin main

          # Clean up
          cd ..
          rm -rf test-azure
