name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test-github
        uses: actions/checkout@v2
      
      - name: Checkiut test-azure
        uses: actions/checkout@v2
        with:
          repository: MSamson-MS/test-azure
