name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: MSamson-MS/test-azure
      
      - name: Set up Git
        run: |
            git config --global user.name "GITHUB_ACTION"
            git config --global user.email "gitaction@github.com"
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: 'Created pull request'
            title: 'Pull Request Title'
            body: 'Pull Request Description'
            branch: test
            base: 'main'
            repository: MSamson-MS/test-azure