name: Auto Create PR in MSamson-MS/test-azure
on:
  pull_request:
    types:
      - opened

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create PR in MSamson-MS/test-azure
        run: |
          git fetch origin
          git checkout -b automatic-pr origin/automatic-pr || git checkout -b automatic-pr
          git push origin automatic-pr

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Automatically create PR
          branch: automatic-pr
          title: Automatically created PR
          body: |
            This PR is automatically created in response to a PR in MSamson-MS/test-github.
            Please review and merge if appropriate.
          base: main
          draft: false
          repository: MSamson-MS/test-azure
