name: Pull Request

on:
  pull_request:
    branches: main

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test-azure
        uses: actions/checkout@v2
        with:
          token: ${{secrets.TOKEN}}
          repository: MSamson-MS/test-azure
          
      - name: Create branch in test-azure
        run: |
            git config --global user.name "Your Name"
            git config --global user.email "youremail@example.com"
            git checkout -b ${{ github.head_ref }}
            git push -u origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        if: github.event_name == 'pull_request'
      
      - name: Merge the current branch in test-github with the new branch in test-azure
        run: |
          sudo apt-get update && sudo apt-get install -y jq

          PR_NUMBER=$(curl -s "${{ github.event.pull_request.url }}" | jq -r '.number')

          RESPONSE=$(curl -s -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -d '{"head": "test-github:'"${{ github.head_ref }}"'", "base": "main"}' \
            "https://api.github.com/repos/MSamson-MS/test-azure/pulls")

          MERGE_STATUS=$(echo $RESPONSE | jq -r '.merged')

          if [[ "$MERGE_STATUS" == "true" ]]; then
            echo "Pull request successfully merged!"
          else
            echo "Failed to merge the pull request."
          fi
