name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  merge_to_azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: 'src'
          repository: 'MSamson-MS/test-github'
          persist-credentials: false
      
      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          path: 'dest'
          repository: 'MSamson-MS/test-azure'
          token: ${{secrets.TOKEN}}
          persist-credentials: true
      
      - name: Copy all the files from src to dest
        run: |
          cp -R src/. dest/

      - name: Commit and push changes
        run: |
          cd dest/
          git config user.name "Your GitHub Username"
          git config user.email "Your GitHub Email"
          git add .
          git commit -m "Merge changes from src"
          git push origin main
