name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  merge_to_azure:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: 'src'
          repository: git@github.com:MSamson-MS/test-github.git
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: false
      
      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          path: 'dest'
          repository: git@github.com:MSamson-MS/test-azure.git
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          token: ${{secrets.TOKEN}}
          persist-credentials: true
      
      - name: Copy common files to new test-azure
        shell: bash
        run: |
          cp -r src/. dest/
      
      - name: Check for new files
        id: newFiles
        shell: bash
        working-directory: dest
        run: |
          git add -A
          git status --porcelain | wc -l
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            echo "::set-output name=hasNewFiles::true"
          else
            echo "::set-output name=hasNewFiles::false"
          fi
        
      - name: Push New Files
        if: ${{ steps.newFiles.outputs.hasNewFiles == 'true' }}
        shell: bash
        working-directory: dest
        run: |
          git config --global user.name "sam[bot]"
          git config --global user.email "sambot@gmail.com"
          git checkout -b test
          git commit -m "Updated common files"
          git push origin test
          
      