name: Pull Request

on:
  pull_request:
    branches: main

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test-azure
        uses: actions/checkout@v2
        with:
          token: ${{secrets.TOKEN}}
          repository: MSamson-MS/test-azure
          
      - name: Create branch in test-azure
        run: |
            cd test-azure
