name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  merge_to_azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: 'src'
          persist-credentials: false
      
      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          path: 'dest'
          repository: MSamson-MS/test-azure
          token: ${{secrets.TOKEN}}
          persist-credentials: true
      
      - name: Copy common files to new test-azure
        shell: bash
        run: |
          cp -r src/. dest/
      
      - name: Check for new files
        id: newFiles
        shell: bash
        working-directory: dest
        run: |
          git add -A
          git status --porcelain | wc -l
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            echo "::set-output name=hasNewFiles::true"
          else
            echo "::set-output name=hasNewFiles::false"
          fi
        
      - name: Push New Files
        if: ${{ steps.newFiles.outputs.hasNewFiles == 'true' }}
        shell: bash
        working-directory: dest
        run: |
          git remote add origin https://sambot:sambot@github.com/MSamson-MS/test-azure.git
          git checkout -b test
          git commit -m "Updated common files"
          git push origin test
          
      