name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  merge_to_azure:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Git config
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
        
      - name: Checkout test-github repository
        uses: actions/checkout@v2

      - name: Clone test-azure repository
        run: |
          git clone https://github.com/MSamson-MS/test-azure.git
          cd test-azure

      - name: Create new branch in test-azure
        run: |
          cd test-azure

          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          git checkout -b azure-branch

          # Push the newly created branch to test-azure repository
          git push origin azure-branch

      - name: Merge pull request branch into azure-branch
        run: |
          cd test-azure

          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
          git checkout azure-branch
          git merge pr-branch

          # Push the merged changes to test-azure repository
          git push origin azure-branch
