name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  merge_to_azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: 'src'
          persist-credentials: false
      
      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          path: 'dest'
          repository: MSamson-MS/test-azure
          token: ${{secrets.TOKEN}}
          persist-credentials: true
      
      - name: Copy common files to new test-azure
        shell: bash
        run: |
          cp -r src/. dest/
      
      - name: Check for changes
        id: check_changes
        run: |
          cd dest
          if [[ -n $(git status -s) ]]; then
            echo "Changes detected in repository"
            echo "::set-output name=changes::true"
          else
            echo "No changes detected in repository"
            echo "::set-output name=changes::false"
          fi
        
      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        working-directory: dest
        run: |
          git remote set-url origin 'MSamson-MS:${{secrets.TOKEN}}@github.com/MSamson-MS/test-azure.git'
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -b update-branch
          git add .
          git commit -m "Update common files"
          git push origin HEAD:update-branch