name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  merge_to_azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: 'src'
          repository: 'MSamson-MS/test-github'
          persist-credentials: false
      
      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          path: 'dest'
          repository: 'MSamson-MS/test-azure'
          token: ${{secrets.TOKEN}}
          persist-credentials: true
      
      - name: Copy common files to new test-azure
        shell: bash
        run: |
          cp -r src/. dest/
      
      - name: Check for new files
        id: newFiles
        shell: bash
        working-directory: dest
        run: |
          git add -A
          git status --porcelain | wc -l
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            echo ":: set-output name=hasNewFiles::true"
          else
            echo ":: set-output name=hasNewFiles::false"
          fi
        
      - name: Push New Files
        if: ${{steps.newFiles.outputs.hasNewFiles == 'true'}}
        shell: bash
        working-directory: dest
        run: |
          git config --global user.name "sam[bot]"
          git config --global user.email "sambot@gmail.com"
          git commit -m "Updated common files"
          git push
          
      