name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  merge_to_azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: 'src'
          repository: 'MSamson-MS/test-github'
          persist-credentials: false
      
      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          path: 'dest'
          repository: 'MSamson-MS/test-azure'
          token: ${{secrets.TOKEN}}
          persist-credentials: true
      
      - name: Create new branch with the same name in dest
        run: |
          cd dest
          BRANCH_NAME=$(echo "${{ github.head_ref }}" | sed 's/refs\/pull\///')
          git checkout -b $BRANCH_NAME
      
      - name: Copy all files from src to the new branch
        run: |
          cp -R src/. dest/
          cd dest
          git config user.name 'Your Name'
          git config user.email 'your-email@example.com'
          git add .
          git commit -m "Copy files from src to the new branch"
      