name: Sync Repos

on:
    pull_request:
        branches:
            - main
    
jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
        
            - name: Set up GitHub CLI
              run: |
                curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
                sudo apt update
                sudo apt install gh
        
            - name: Configure GitHub CLI
              run: |
                gh config set prompt disabled
                gh auth login --with-token < ${{secrets.TOKEN}}
        
           