name: Pull Request

on:
  pull_request:
    branches: main

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test-azure
        uses: actions/checkout@v2
        with:
          token: ${{secrets.TOKEN}}
          repository: MSamson-MS/test-azure

      - name: Create branch in test-azure
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git fetch test-azure
          git checkout -B ${{ github.head_ref }} test-azure/main
          git push -f test-azure ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request'